import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="gtag-manager"
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-ZB1RNZR8WF"
        />
        <Script id="init-gtag">
          {`window.dataLayer = window.dataLayer || [];` +
            `function gtag(){dataLayer.push(arguments);}` +
            `gtag('js', new Date());` +
            `gtag('config', 'G-ZB1RNZR8WF');`}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}
